<Project>
  <!-- Legacy projects: Configuration is available after the .csproj is loaded -->
  <PropertyGroup Condition="'$(UsingMicrosoftNETSdk)' != 'true'">
    <OutputPath>$(BaseOutputPath)$(Configuration)\</OutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)$(Configuration)\</IntermediateOutputPath>
  </PropertyGroup>
</Project>
